### ISSUE TITLE
more buttons Windows

### ISSUE THREAD

**Issue by ramaxa9** [milador/CircuitPython_XAC_Gamepad#1]
hello, I am new to programing
how I can modify this to have more then 8 buttons(I need 32 or more) in Windows?

when I change this in `boot.py`:

> 0x95, 0x20,  #   Report Count (8) ` new value 0x20`
> 0x05, 0x09,  #   Usage Page (Button)
> 0x19, 0x01,  #   Usage Minimum (0x01)
> 0x29, 0x20,  #   Usage Maximum (0x08) ` new value 0x20`

I can see 32 buttons in windows Devices and printers> Pico> Game controllers, but the buttons not work there

but it works just fine in Linux

**Comment by milador** [comment]
You will need to change the Hid_XAC_Gamepad.py code as well. It’s written to handle only 3 bytes ( 1 byte for 8 buttons and 2 for joystick). You will need to change it to accept 6 bytes and handle the button press for other additional buttons.Hope this helps.

**Comment by ramaxa9** [comment]
thank You for reply! xD

so for 32 buttons i need 4 bytes report? (no axis needed)
> self._report = bytearray(4)
> self._last_report = bytearray(4)

it throw an error:
> Traceback (most recent call last):
>   File "code.py", line 29, in <module>
>   File "hid_xac_gamepad.py", line 60, in __init__
>   File "hid_xac_gamepad.py", line 91, in reset_all
>   File "hid_xac_gamepad.py", line 101, in _send
> ValueError: Buffer incorrect size. Should be 3 bytes.

this is the code
```
def _send(self, always=False):
        """Send a report with all the existing settings.
        If ``always`` is ``False`` (the default), send only if there have been changes.
        """

        struct.pack_into('<BBB', self._report, 0, self._buttons_state)

        if always or self._last_report != self._report:
            self._gamepad_device.send_report(self._report)

            # Remember what we sent, without allocating new storage.
            self._last_report[:] = self._report
```


full code here:
<details>
<summary>code.py</summary>

```
# SPDX-FileCopyrightText: 2021 ladyada for Adafruit Industries
# SPDX-License-Identifier: MIT

"""
====================================================

* Author(s): Adafruit Industries
* Edited: Milad Hajihassan
"""

# Setup and usage Guide in details:

# 1) Install CircuitPython 7 or above in your board : https://circuitpython.org/downloads
# 2) Add the __init__.py file under \lib\adafruit_hid directory of CIRCUITPY drive
# 3) Add the boot.py file inside main directory of CIRCUITPY drive
# 4) Add the code.py file inside main directory of CIRCUITPY drive
# 5) Add the hid_xac_gamepad.py file inside main directory of CIRCUITPY drive
# 6) Hard reset the board using the reset button or software reset.
# You may need to remove the device in Windows for it to update the HID profile

import time
import board
import digitalio
import analogio
import usb_hid

from hid_xac_gamepad import Gamepad

gp = Gamepad(usb_hid.devices)

# Create some buttons. The physical buttons are connected
# to ground on one side and these and these pins on the other.
button_pins = (board.GP2, board.GP6, board.GP10,)

# Map the buttons to button numbers on the Gamepad.
# gamepad_buttons[i] will send that button number when buttons[i]
# is pushed.
gamepad_buttons = (1, 2, 3,)

buttons = [digitalio.DigitalInOut(pin) for pin in button_pins]
for button in buttons:
    button.direction = digitalio.Direction.INPUT
    button.pull = digitalio.Pull.UP


while True:
    # Buttons are grounded when pressed (.value = False).
    for i, button in enumerate(buttons):
        gamepad_button_num = gamepad_buttons[i]
        if not button.value:
            gp.press_buttons(gamepad_button_num)
            print(" pressed", gamepad_button_num, end="")
        if button.value:
            gp.release_buttons(gamepad_button_num)
            print(" released", gamepad_button_num, end="")

    time.sleep(0.1)
```

</details>

<details>
<summary>boot.py</summary>

```
# SPDX-FileCopyrightText: 2021 Milador
#
# SPDX-License-Identifier: MIT

"""
`Gamepad`
====================================================

* Author(s): Milad Hajihassan
"""

import usb_hid
import usb_midi
import usb_cdc
import storage

storage.remount("/", readonly=False)

m = storage.getmount("/")
m.label = "ETS_CP"

storage.remount("/", readonly=True)

storage.enable_usb_drive()

XAC_GAMEPAD_REPORT_DESCRIPTOR = bytes((
    0x05, 0x01,  # Usage Page (Generic Desktop Ctrls)
    0x09, 0x05,  # Usage (GamePad)
    0xA1, 0x01,  # Collection (Application)
    0x85, 0x05,  #   Report ID (5)
    0x15, 0x00,  #   Logical Minimum (0)
    0x25, 0x01,  #   Logical Maximum (1)
    0x35, 0x00,  #   Physical Minimum (0)
    0x45, 0x01,  #   Physical Maximum (1)
    0x75, 0x01,  #   Report Size (4)
    # 0x95, 0x08,  #   Report Count (8)
    0x95, 0x20,  #   Report Count (32)
    0x05, 0x09,  #   Usage Page (Button)
    0x19, 0x01,  #   Usage Minimum (0x01)
    # 0x29, 0x08,  #   Usage Maximum (0x08)
    0x29, 0x20,  #   Usage Maximum (0x08)
    0x81, 0x02,  #   Input (Data,Var,Abs,No Wrap,Linear,Preferred State,No Null Position)
    # 0x05, 0x01,  #   Usage Page (Generic Desktop Ctrls)
    # 0x26, 0xFF, 0x00,  #   Logical Maximum (255)
    # 0x46, 0xFF, 0x00,  #   Physical Maximum (255)
    # 0x09, 0x30,  #   Usage (X)
    # 0x09, 0x31,  #   Usage (Y)
    # 0x75, 0x08,  #   Report Size (8)
    # 0x95, 0x02,  #   Report Count (2)
    # 0x81, 0x02,  #   Input (Data,Var,Abs,No Wrap,Linear,Preferred State,No Null Position)
    0xC0,        # End Collection
))

xac_gamepad = usb_hid.Device(
    report_descriptor=XAC_GAMEPAD_REPORT_DESCRIPTOR,
    usage_page=0x01,           # Generic Desktop Control
    usage=0x05,                # Gamepad
    report_ids=(5,),           # Descriptor uses report ID 5.
    in_report_lengths=(3,),    # This gamepad sends 3 bytes in its report.
    out_report_lengths=(0,),   # It does not receive any reports.
)

# Disable CDC if needed
# usb_cdc.disable()

# Disable midi if needed
usb_midi.disable()

usb_hid.enable((xac_gamepad,))


```

</details>

<details>
<summary>hid_xac_gamepad.py</summary>

```
# SPDX-FileCopyrightText: 2018 Dan Halbert for Adafruit Industries
#
# SPDX-License-Identifier: MIT

"""
`Gamepad`
====================================================

* Author(s): Dan Halbert
* Edited: Milad Hajihassan
"""
import sys
if sys.implementation.version[0] < 7:
    raise ImportError('{0} is not supported in CircuitPython 7.x or lower'.format(__name__))

import struct
import time

from adafruit_hid import find_device


class Gamepad:
    """Emulate a generic gamepad controller with 8 buttons,
    numbered 1-8 and one joystick controlling
    ``x` and ``y`` values.

    The joystick values could be interpreted
    differently by the receiving program: those are just the names used here.
    The joystick values are in the range 0 to 255.
"""

    def __init__(self, devices):
        """Create a Gamepad object that will send USB gamepad HID reports.

        Devices can be a list of devices that includes a gamepad device or a gamepad device
        itself. A device is any object that implements ``send_report()``, ``usage_page`` and
        ``usage``.
        """
        self._gamepad_device = find_device(devices, usage_page=0x1, usage=0x05)

        # Reuse this bytearray to send mouse reports.
        # Typically controllers start numbering buttons at 1 rather than 0.
        # report[0] buttons 1-8 (LSB is button 1)
        # report[1] joystick 0 x: 0 to 255
        # report[2] joystick 0 y: 0 to 255
        self._report = bytearray(4)

        # Remember the last report as well, so we can avoid sending
        # duplicate reports.
        self._last_report = bytearray(4)

        # Store settings separately before putting into report. Saves code
        # especially for buttons.
        self._buttons_state = 0


        # Send an initial report to test if HID device is ready.
        # If not, wait a bit and try once more.
        try:
            self.reset_all()
        except OSError:
            time.sleep(1)
            self.reset_all()

    def press_buttons(self, *buttons):
        """Press and hold the given buttons. """
        for button in buttons:
            self._buttons_state |= 1 << self._validate_button_number(button) - 1
        self._send()

    def release_buttons(self, *buttons):
        """Release the given buttons. """
        for button in buttons:
            self._buttons_state &= ~(1 << self._validate_button_number(button) - 1)
        self._send()

    def release_all_buttons(self):
        """Release all the buttons."""

        self._buttons_state = 0
        self._send()

    def click_buttons(self, *buttons):
        """Press and release the given buttons."""
        self.press_buttons(*buttons)
        self.release_buttons(*buttons)

    def reset_all(self):
        """Release all buttons and set joystick to zero."""
        self._buttons_state = 0
        self._send(always=True)

    def _send(self, always=False):
        """Send a report with all the existing settings.
        If ``always`` is ``False`` (the default), send only if there have been changes.
        """

        struct.pack_into('<BBB', self._report, 0, self._buttons_state)

        if always or self._last_report != self._report:
            self._gamepad_device.send_report(self._report)

            # Remember what we sent, without allocating new storage.
            self._last_report[:] = self._report

    @staticmethod
    def _validate_button_number(button):
        if not 1 <= button <= 32:
            raise ValueError("Button number must in range 1 to 32")
        return button

```

</details>

**Comment by ramaxa9** [comment]
oh ... i missed this
`in_report_lengths=(3,),`

now it send keypresses 1-8, but it throw an error on  9-32 buttons
> Traceback (most recent call last):
>   File "code.py", line 51, in <module>
>   File "hid_xac_gamepad.py", line 69, in press_buttons
>   File "hid_xac_gamepad.py", line 98, in _send
> OverflowError: value must fit in 1 byte(s)

i assume i have to change something here
`struct.pack_into('<BBB', self._report, 0, self._buttons_state)`

**Comment by ramaxa9** [comment]
i changed this '<BBB' to '<I' , and now it works!
![image](https://user-images.githubusercontent.com/18683778/151636029-eb4ac836-e86e-4476-a0bc-9ff12f42b2c8.png)

not sure what this means but it have size of 4 so i tried and miracle happens! xD

Thank You!

**Comment by ramaxa9** [comment]
i changed report to 8 bytes and `struct.pack_into('<Q', self._report, 0, self._buttons_state)`
and now i have 64 buttons! xD

**Comment by milador** [comment]
@ramaxa9 Great work! Sorry for late reply. Yes, each size indicates a byte. The key is to make sure you don't mess the order buttons with joystick axis's. Now ,it's easier if you just have buttons and you just want to make sure the number of buttons in the report match the number of bytes. It seems you got it. Let me know if you run to other issues.
